
cloud_name: 'cloudinary_name'
api_key: 'cloudinary_key'
api_secret: 'cloudinary_secret'

clip_length: 14  # in seconds
clip_folder: '_temp/' # clips temporally folder. They will be deleted once uploaded to Cloudinary
